Silence compiler warnings
```bash
g++ -O2 -Wall -pedantic -Wextra -Werror -Wno-unused-parameter -Wno-long-long -mpopcnt -DHAVE_POPCNT -mavx2 -DHAVE_AVX2 test.cpp -o test
In file included from test.cpp:7:0:
libpopcnt.h: In function 'int main(int, char**)':
libpopcnt.h:89:18: error: 'ebx' may be used uninitialized in this function [-Werror=maybe-uninitialized]
      "+d" (*edx));
                  ^
libpopcnt.h:103:16: note: 'ebx' was declared here
   unsigned int ebx;
                ^
libpopcnt.h:89:18: error: 'edx' may be used uninitialized in this function [-Werror=maybe-uninitialized]
      "+d" (*edx));
                  ^
libpopcnt.h:105:16: note: 'edx' was declared here
   unsigned int edx;
                ^
cc1plus.exe: all warnings being treated as errors
Makefile:13: recipe for target 'avx2' failed
make: *** [avx2] Error 1
```